package com.bhardwaj.wish

enum class WishesStyles {
    SUCCESS,
    INFORMATION,
    WARNING,
    ERROR,
    DELETE,
    NO_INTERNET,
    COLORED_SUCCESS,
    COLORED_INFORMATION,
    COLORED_WARNING,
    COLORED_ERROR,
    COLORED_DELETE,
    COLORED_NO_INTERNET
}